Созданы классы и их функционал
Students-of-the-city-of-Kostroma/KSU.Visio pull request #19
Opened 2019-12-14 06:21 UTC by KudelinRoman

#18

2019-12-14 06:22 UTC, KudelinRoman commented
Здравствуйте, пожалуйста проверьте и скажите что нам необходимо еще доделать.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2019-12-23 18:58 UTC, YuriSilenok requested changes

2019-12-23 18:58 UTC, YuriSilenok commented on KSU.Visio.Lib/Components.cs
> +		}
зачем вы здесь переопределяете метод точно таким же кодом как и в родительском классе?

2019-12-23 19:12 UTC, KudelinRoman commented on KSU.Visio.Lib/Components.cs
> +		}
Здравствуйте.
Этот код проверяет попадает ли данная фигура на наш холст.
Он использует верхний левый угол, именно с этого угла начинается рисование фигуры, проверяет ширину и высоту. Проверяет чтобы фигура полностью располагалась на холсте.
Спасибо. 
Куделин Роман.
17-ИСбо-2б.

2019-12-23 19:15 UTC, YuriSilenok commented on KSU.Visio.Lib/Components.cs
> +		}
Добрый день,

спасибо что рассказали что делает метод Hit_testing в дочернем классе. Могли бы вы пояснить, в чем отличие от метода Hit_testing в родительском классе Figure?

2019-12-23 19:20 UTC, KudelinRoman commented on KSU.Visio.Lib/Components.cs
> +		}
Здравствуйте.
Отличий никаких нет.
Я так понимаю необходимо удалить метод Hit_testing в дочернем классе?
Спасибо. 
Куделин Роман.
17-ИСбо-2б.

2019-12-23 19:21 UTC, YuriSilenok commented on KSU.Visio.Lib/Components.cs
> +		}
не только в нем, есть и другие дочерние классы

2019-12-23 19:22 UTC, KudelinRoman commented on KSU.Visio.Lib/Components.cs
> +		}
Здравствуйте.
Завтра к обеду думаю будет выполнено.
Спасибо.
Куделин Роман.
17-Исбо-2б.

2019-12-24 05:12 UTC, YuriSilenok requested changes
Зачем вы снова отдали на проверку, ничего не исправив?

2019-12-30 22:18 UTC, MaximTrapeznikov commented
Здравствуйте.

Запушил с другого аккаунта по причине того, что делал не со своего компьютера, так как не находился дома, а глобальные настройки забыл поменять.

Спасибо.
Трапезников Максим.
17-ИСбо-2б.

2020-01-03 15:15 UTC, YuriSilenok requested changes
Обратите внимание на замечания

2020-01-03 15:15 UTC, YuriSilenok commented on KSU.Visio.Lib/Figure.cs
> +	}
Почему этот метод появился, где он используется?

2020-01-03 15:15 UTC, YuriSilenok commented on KSU.Visio.Lib/Limitation.cs
> +	}
Почему этот метод появился, где он используется?

2020-01-03 15:15 UTC, YuriSilenok commented on KSU.Visio.Lib/Rectangle_object.cs
> +	}
Почему этот метод появился, где он используется?

2020-01-03 15:15 UTC, YuriSilenok commented on KSU.Visio.Lib/Cap/Dependence.cs
> +	public class Dependence: LineCapBase
XML-документация

2020-01-03 15:15 UTC, YuriSilenok commented on KSU.Visio.Lib/Cap/Interface.cs
> +	public class Interface: LineCapBase
XML-документация

2020-01-03 15:15 UTC, YuriSilenok commented on KSU.Visio.Lib/Components.cs
> +		public Components(Point location, Size size) : base(location, size)
XML-документация

2020-01-03 15:15 UTC, YuriSilenok commented on KSU.Visio.Lib/KSU.Visio.Lib.csproj
> +    <Compile Include="Cap\Interface.cs" />
Названия должны быть осмысленные

2020-01-03 15:15 UTC, YuriSilenok commented on KSU.Visio.Lib/KSU.Visio.Lib.csproj
> +    <Compile Include="Components.cs" />
Не найден на диаграмме

2020-01-03 19:59 UTC, KudelinRoman commented on KSU.Visio.Lib/Rectangle_object.cs
> +	}
Здравствуйте.
Этот метод появился потому что он есть в диаграмме классов.
![image](https://user-images.githubusercontent.com/47320335/71745839-61366a80-2e7c-11ea-824e-34db0c9ca647.png)
Используется для проверки попадания точки внутрь прямоугольной области фигуры
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-03 20:01 UTC, KudelinRoman commented on KSU.Visio.Lib/KSU.Visio.Lib.csproj
> +    <Compile Include="Components.cs" />
Здравствуйте.
![image](https://user-images.githubusercontent.com/47320335/71745995-db66ef00-2e7c-11ea-8f97-59c990417900.png)
Это он на диаграмме. Отличие в одну букву.
Можно ли оставить так? Или необходимо переименовать?
Спасибо.
Куделин Роман
17-ИСбо-2б.

2020-01-03 20:04 UTC, KudelinRoman commented on KSU.Visio.Lib/KSU.Visio.Lib.csproj
> +    <Compile Include="Cap\Interface.cs" />
Здравствуйте.
Названия давали осмысленно.
![image](https://user-images.githubusercontent.com/47320335/71746178-3bf62c00-2e7d-11ea-84a3-242a8f3bee47.png)
Если не так, то как должны били называться эти классы?
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-03 20:08 UTC, KudelinRoman commented on KSU.Visio.Lib/Limitation.cs
> +	}
Здравствуйте.
Случайно пропустили.
Удалим. 
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-03 20:10 UTC, KudelinRoman commented on KSU.Visio.Lib/Figure.cs
> +	}
Здравствуйте.
Метод появился потому что он есть на диаграмме классов.
![image](https://user-images.githubusercontent.com/47320335/71746477-13226680-2e7e-11ea-9142-0e65abfe4f8d.png)
Использоваться будет для проверки попадает ли точка внутрь прямоугольной области фигуры.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-03 20:11 UTC, KudelinRoman commented on KSU.Visio.Lib/Cap/Dependence.cs
> +	public class Dependence: LineCapBase
Здравствуйте.
В чем проблема? Опиши пожалуйста поподробнее.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-05 17:28 UTC, YuriSilenok commented on KSU.Visio.Lib/Cap/Dependence.cs
> +	public class Dependence: LineCapBase
Привет,

Проблема в отсутствии XML-документации.

Спасибо,
Юрий

2020-01-05 17:39 UTC, YuriSilenok commented on KSU.Visio.Lib/Rectangle_object.cs
> +	}
Добрый день,

Допустим, хотя есть стандартный метод для этого, но раз он есть на диаграмме...

Спасибо,
Юрий

2020-01-05 17:41 UTC, YuriSilenok commented on KSU.Visio.Lib/KSU.Visio.Lib.csproj
> +    <Compile Include="Cap\Interface.cs" />
Добрый день,

интерфейс имеет ввиду интерфейс как элемент диаграммы или как особый тип класса в программировании. Это не ясно без XML-документации

Спасибо,
Юрий

2020-01-05 17:42 UTC, YuriSilenok commented on KSU.Visio.Lib/KSU.Visio.Lib.csproj
> +    <Compile Include="Components.cs" />
Добрый день,

переименуйте в коде, это не долго

Спасибо,
Юрий

2020-01-06 18:36 UTC, KudelinRoman commented on KSU.Visio.Lib/Cap/Dependence.cs
> +	public class Dependence: LineCapBase
Здравствуйте.
Правильно ли я понимаю, что  XML-документация это комментарий?
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-06 18:41 UTC, KudelinRoman commented on KSU.Visio.Lib/KSU.Visio.Lib.csproj
> +    <Compile Include="Cap\Interface.cs" />
Здравствуйте.
Интерфейс имеет ввиду как элемент диаграммы.
Уточним в  XML-документации.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-13 19:59 UTC, KudelinRoman commented on KSU.Visio.Lib/Limitation.cs
> +	}
Здравствуйте.
Исправлено.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-20 06:23 UTC, YuriSilenok commented
я не смогу проверить, пока вы повторно не запросите проверку

2020-01-21 06:26 UTC, YuriSilenok reviewed
А что с XML документацией?

2020-01-22 17:43 UTC, KudelinRoman commented
> А что с XML документацией?

Здравствуйте.
По поводу XML документации мы задали вам вопрос и ожидаем ответа.
Вопрос "Правильно ли я понимаю, что XML-документация это комментарий?"
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-01-27 08:06 UTC, YuriSilenok commented on KSU.Visio.Lib/Cap/Dependence.cs
> +	public class Dependence: LineCapBase
> Правильно ли я понимаю, что XML-документация это комментарий?

https://docs.microsoft.com/ru-ru/dotnet/csharp/codedoc#summary

Обязательно наличие Тега <summary

2020-01-27 08:07 UTC, YuriSilenok commented
> > А что с XML документацией?
> 
> Здравствуйте.
> По поводу XML документации мы задали вам вопрос и ожидаем ответа.
> Вопрос "Правильно ли я понимаю, что XML-документация это комментарий?"
> Спасибо.
> Куделин Роман.
> 17-ИСбо-2б.

Ответил [здесь](https://github.com/Students-of-the-city-of-Kostroma/KSU.Visio/pull/19#discussion_r371101668)

2020-02-09 19:27 UTC, YuriSilenok requested changes
Исправить

2020-02-09 19:27 UTC, YuriSilenok commented on KSU.Visio.Lib/Cap/Dependence.cs
> +		public Dependence() : base()
Добрый день,

Здесь нет документации кода.

Спасибо,
Юрий

2020-02-09 19:27 UTC, YuriSilenok commented on KSU.Visio.Lib/Line.cs
> +	}
А к какому объекту этот комментарий?

2020-02-09 19:27 UTC, YuriSilenok commented on KSU.Visio.Lib/Package.cs
> +		/// Конструктор класса "Пакет"
если меня попросят дать характеристику на Вас, я должен буду написать в ней: "Студент КГУ"?
Опишите что делает этот конструктор

2020-02-16 06:09 UTC, YuriSilenok requested changes
Добрый день,

пожалуйста, если есть замечание к одному методу, то нужно проверить, это и к другим методам.
комментарий должны отвечать на вопрос "Зачем нужен этот класс, конструктор, метод и т.д."

Спасибо,
Юрий

2020-02-16 06:09 UTC, YuriSilenok commented on KSU.Visio.Lib/Cap/Interface.cs
> +		public Interface ():base()
здесь не хватает комментарий к конструктору

2020-02-16 06:09 UTC, YuriSilenok commented on KSU.Visio.Lib/Cap/Interface.cs
> +	public class Interface: LineCapBase
в комментариях написать зачем этот класс

2020-02-16 06:09 UTC, YuriSilenok commented on KSU.Visio.Lib/Component.cs
> +	public class Component :Figure
в комментариях написать зачем этот класс

2020-03-02 12:11 UTC, YuriSilenok requested changes
Пожалуйста, в комментариях пишите какую функциональную роль выполняет тот или иной объект. Не нужно писать о родителях в описании конструктора

2020-03-02 12:11 UTC, YuriSilenok commented on KSU.Visio.Lib/Component.cs
> +	public class Component :Figure
Я оджидал здесь появление более развернутого описания предназначения класса

2020-03-02 12:11 UTC, YuriSilenok commented on KSU.Visio.Lib/Component.cs
> +		public override Figure Clone()
Публичные объекты должны иметь комментарий

2020-03-02 12:11 UTC, YuriSilenok commented on KSU.Visio.Lib/Limitation.cs
> +	/// Класс "ограничение"
Требуется более развернутый ответ о предназначенииэтого класса.

2020-03-07 06:11 UTC, KudelinRoman commented on KSU.Visio.Lib/Cap/Interface.cs
> +		public Interface ():base()
Здравствуйте.
Комментарий к этому конструктору был добавлен.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-03-09 16:35 UTC, YuriSilenok requested changes
есть замечания

2020-03-09 16:35 UTC, YuriSilenok commented on KSU.Visio.Lib/Line.cs
> +	}
вернуть в исходное состояние, не создавайте лишних изменений в коде. это приводит к конфликтам

2020-03-09 16:35 UTC, YuriSilenok commented on KSU.Visio.Lib/Rectangle_object.cs
> +		public override bool Hit_testing(Point Point)
публичные объекты должны иметь комментарии

2020-03-09 16:35 UTC, YuriSilenok commented on KSU.Visio/Start.cs
> +			// элементы
зачем пробел и о чем должен говорить этот комментарий?

2020-03-16 11:28 UTC, YuriSilenok requested changes
нет комментария и обнаружены дублирующие методы

2020-03-16 11:28 UTC, YuriSilenok commented on KSU.Visio.Lib/Rectangle_object.cs
>    public class Rectangle_object : Figure
Нет комментария для публичного класса

2020-03-16 11:28 UTC, YuriSilenok commented on KSU.Visio.Lib/Rectangle_object.cs
> +	}
Дубликат родителя

2020-03-16 11:28 UTC, YuriSilenok commented on KSU.Visio.Lib/Restriction_OR.cs
> +		}
дубликат родителя

2020-03-19 12:07 UTC, KudelinRoman commented
Здравствуйте.
Если есть еще ошибки и замечания, пожалуйста напишите все сразу, а не по 3-5 штук. 
Если вы напишите все ошибки и замечания разом, я думаю это уменьшит время выполнения этой задачи.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-03-23 07:43 UTC, YuriSilenok commented
Добрый день, Роман,

> Если есть еще ошибки и замечания, пожалуйста напишите все сразу, а не по 3-5 штук.

Я буду писать по 3 штуки, так как Вы не стремитесь перепроверять код на предмет подобных ошибок. Если я указал Вам на дубликат метода, почему Вы не можете пойти и проверить что таких дубликатов больше нет, почему вы не можете проверить сразу все публичные объекты на предмет наличия комментариев.

Спасибо,
Юрий

2020-03-23 07:51 UTC, YuriSilenok requested changes
Вы на финишной прямой.
Но, есть замечания.

2020-03-23 07:51 UTC, YuriSilenok commented on KSU.Visio.Lib/Figure.cs
>      public abstract class Figure
Публичный класс не имеет комментария

2020-03-23 07:51 UTC, YuriSilenok commented on KSU.Visio/Start.Designer.cs
> +			this.groupBox1.ResumeLayout(false);
запрос не связан с изменением этого файла, пожалуйста, верните его в первоначальное состояние.

2020-03-23 19:53 UTC, KudelinRoman commented on KSU.Visio.Lib/Rectangle_object.cs
>    public class Rectangle_object : Figure
Здравствуйте.
Эта проблема уже считается решенной?
Или мы допустили ошибки и необходимо исправить?
Спасибо.
Куделин Роман.
17-ИСбо-2б.

2020-03-23 20:07 UTC, KudelinRoman commented
Здравствуйте.
> Если я указал Вам на дубликат метода, почему Вы не можете пойти и проверить что таких дубликатов больше нет, почему вы не можете проверить сразу все публичные объекты на предмет наличия комментариев.

Если необходимо исправлять в других методах подобные ошибки которые вы указали, мы думаем что вы нам об этом напишите, как писали один раз(прилагаю скриншот).
![image](https://user-images.githubusercontent.com/47320335/77358296-a6bb5300-6d5a-11ea-8d9f-e0d7bad7d308.png)
То есть если вы нам пишите, что необходимо исправить ошибки в методе/классе который вы указали и не пишите что такие же ошибки содержаться в других методах/классах, то мы думаем, что ошибка относится только к этому методу/классу и в других классах/методах это не считается за ошибку.
Спасибо.
Куделин Роман
17-ИСбо-2б.

2020-03-26 21:36 UTC, KudelinRoman commented on KSU.Visio/Start.Designer.cs
> +			this.groupBox1.ResumeLayout(false);
Здравствуйте.
Можете описать поподробнее что нам необходимо сделать.
Спасибо.
Куделин Роман
17-ИСбо-2б.

2020-04-07 14:00 UTC, YuriSilenok approved these changes
Мержите

2020-04-07 17:39 UTC, merged